[project]
name = "libguard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "celery>=5.6.2",
    "django>=6.0.2",
    "django-rest-framework>=0.1.0",
    "python-decouple>=3.8",
]
